FROM python:3.12.3

RUN pip install flask pandas numpy scipy scikit-learn matplotlib seaborn

WORKDIR /uygulama

COPY . .

COPY breast-cancer.csv /uygulama/ML_Example/breast-cancer.csv

CMD ["python", "main.py"]
